pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        script {
          dockerImage = docker.build("your-username/your-app-name:${env.BUILD_ID}")
        }
      }
    }
    stage('Test') {
      steps {
        sh 'npm test'
      }
    }
    stage('Push') {
      steps {
        script {
          docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
            dockerImage.push("${env.BUILD_ID}")
            dockerImage.push("latest")
          }
        }
      }
    }
    stage('Deploy') {
      steps {
        sh 'kubectl apply -f deployment.yaml'
        sh 'kubectl apply -f service.yaml'
      }
    }
  }
}
